version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
        - ./:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8080"

    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    env_file:
      - .env

  redis:
    image: redis:alpine


  celery:
    build:
      context: .
    command: "celery -A library_service_api worker --loglevel=info -P eventlet"
    env_file:
      - .env
    depends_on:
      - redis
      - app
      - db


  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: "celery -A library_service_api beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    depends_on:
      - app
      - redis
      - db
      - celery
    restart: on-failure
    env_file:
      - .env
